### ISSUE TITLE
更新报错

### ISSUE THREAD

**Issue by BarretWu** [jenly1314/AppUpdater#34]
Fatal Exception: java.lang.RuntimeException: Unable to start service com.king.app.updater.service.DownloadService@c59091c with Intent { cmp=com.wwyy.wzhxl/com.king.app.updater.service.DownloadService }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.king.app.updater.UpdateConfig.l()' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4107)
       at android.app.ActivityThread.access$1800(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1893)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7403)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by jenly1314** [comment]
贴个混淆了的代码，是认真的？
